In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [5]:
data = pd.read_csv('Dataset/multiple linear regression.csv')

In [6]:
y = data['GPA']
x= data[['SAT', 'Rand 1,2,3']]

In [7]:
reg = LinearRegression()

In [8]:
reg.fit(x, y)

LinearRegression()

In [9]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [10]:
reg.intercept_

0.29603261264909353

In [11]:
reg.score(x, y) # R-squared

0.4066811952814282

### Formula for Adjusted $R^2$

$R_{adjusted}^2 = 1 - (1 - R^2) * \frac{n-1}{n-p-1}$

notes: **n** = number of observations | **p** = number of predictor

In [12]:
r2 = reg.score(x, y)
n = x.shape[0]
p = x.shape[1]

def adjusted_r_sq(n, p, r2):
    return 1-(1-r2)*(n-1)/(n-p-1)

In [13]:
adjusted_r_sq(n, p, r2)

0.39203134825134

Feature Selection through p-values

In [14]:
from sklearn.feature_selection import f_regression

In [15]:
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [16]:
p_values = f_regression(x, y)[1]

In [17]:
p_values

array([7.19951844e-11, 6.76291372e-01])

In [18]:
p_values.round(4)

array([0.    , 0.6763])

Creating Summary Table

In [19]:
reg_summary = pd.DataFrame(data= x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [20]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(4)
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654    0.0000
1  Rand 1,2,3     -0.008270    0.6763

### Standardization

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()

In [25]:
# fit calculates the mean & std of each feature
scaler.fit(x)

StandardScaler()

In [28]:
# .transform() transforms the unscaled inputs using the information contained in the scaler object (feature-wise)
x_scaled = scaler.transform(x)

### Regression with Scaled Features

In [30]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [31]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [32]:
reg.intercept_

3.330238095238095

In [35]:
reg_summary = pd.DataFrame([['Intercept'], ['SAT'], ['Rand 1,2,3']], columns= ['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

# Weights also known as coefficients
# The bigger the weights, the bigger the impact of the feature on the regression
# Intercept is also called bias, the idea is the intercept is nothing but just a mere number, which adjust our regression with some constant

In [36]:
reg_summary

Features   Weights
0   Intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

### Making predictions with standardized weights

In [37]:
new_data = pd.DataFrame(data= [[1700, 2], [1800, 1]], columns= ['SAT', 'Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [38]:
new_data_scaled = scaler.transform(new_data)
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [39]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:, 0].reshape(-1, 1)
reg_simple.fit(x_simple_matrix, y)

LinearRegression()

In [40]:
reg_simple.predict(new_data_scaled[:, 0].reshape(-1, 1))

array([3.08970998, 3.25527879])