In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
# Load data
data = pd.read_csv('Dataset/simple linear reg.csv')

In [4]:
x = data['SAT'] # This is the input, a.k.a the "FEATURE"
y = data['GPA'] # This is the output, a.k.a the "TARGET"


In [5]:
print(x.shape)
print(y.shape)

(84,)
(84,)


In [6]:
reg = LinearRegression()


In [22]:
x_matrix = x.values.reshape(-1, 1)
y_matrix = y.values.reshape(-1, 1)

In [29]:
reg.fit(x_matrix, y_matrix)
reg.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

In [24]:
# This is the r-squared
reg.score(x_matrix, y_matrix)

0.40600391479679765

In [25]:
# This is the Coefficients
reg.coef_

array([[0.00165569]])

In [26]:
# Intercept
reg.intercept_

array([0.2750403])

In [28]:
# Making predictions
reg.predict([[1740]])

array([[3.15593751]])

Making predictions

In [30]:
new_data = pd.DataFrame(data= [1740, 1760], columns=['SAT'])
new_data

SAT
0  1740
1  1760

In [31]:
reg.predict(new_data)

array([[3.15593751],
       [3.18905127]])

In [32]:
new_data['Predicted GPA'] = reg.predict(new_data)

In [37]:
import random

In [45]:
new_data2 = pd.DataFrame(data= np.random.randint(1600, 1800, 100), columns=['SAT'])

In [46]:
new_data2['Predicted GPA'] = reg.predict(new_data2)

In [47]:
new_data2

SAT  Predicted GPA
0   1729       3.137725
1   1701       3.091366
2   1762       3.192363
3   1756       3.182429
4   1669       3.038384
..   ...            ...
95  1793       3.243689
96  1780       3.222165
97  1700       3.089710
98  1706       3.099644
99  1757       3.184084

[100 rows x 2 columns]